name: UltimateBows
version: '${project.version}'
main: me.nssj.ultimatebows.UltimateBows
api-version: 1.19
authors: [nSSj_]
description: Add different types of bows into your Minecraft server
commands:
  ubows:
    description: Gives the player a custom bow
    usage: /<command>
    permission: ultimatebows.give

